<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RootNamespace>MistMapper.Host</RootNamespace>
    <AssemblyName>MistMapper</AssemblyName>
    <ApplicationIcon>Assets\MistMapper.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\MistMapper.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\MistMapper.ico" LogicalName="MistMapper.Host.Assets.MistMapper.ico" />
  </ItemGroup>

</Project>
